name: test
on: [push]
jobs:
  install_job:
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.6, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install .
      - run: pip install pytest
      - run: pip install git+https://github.com/boudinfl/pke.git
      - run: pip install nltk
      - run: pip install spacy
      - run: python -m spacy download en_core_web_lg
      - run: pip install PyMuPDF
      - run: pip install textract
      - run: pip install pdfminer
      - run: pip install openpyxl 
      - run: pytest test/
      
      
